// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApRcwZ8nFQYkMLO4tNVvEnN_vBGRtgPPw',
    appId: '1:679818120383:web:5f73ee623d4b7ac8eb0a0a',
    messagingSenderId: '679818120383',
    projectId: 'gamestagram-1b697',
    authDomain: 'gamestagram-1b697.firebaseapp.com',
    storageBucket: 'gamestagram-1b697.firebasestorage.app',
    measurementId: 'G-ZNT72KZ16N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWD1tVhQ4_5oiEiatYlJwwROvhj7rhdyQ',
    appId: '1:679818120383:android:cc3da9b71932a581eb0a0a',
    messagingSenderId: '679818120383',
    projectId: 'gamestagram-1b697',
    storageBucket: 'gamestagram-1b697.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2NjkAMJhB2Ib3A9pf1osi7x9EFKRsgtc',
    appId: '1:679818120383:ios:9c42e92bf73f26c9eb0a0a',
    messagingSenderId: '679818120383',
    projectId: 'gamestagram-1b697',
    storageBucket: 'gamestagram-1b697.firebasestorage.app',
    iosBundleId: 'com.example.gamestagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2NjkAMJhB2Ib3A9pf1osi7x9EFKRsgtc',
    appId: '1:679818120383:ios:9c42e92bf73f26c9eb0a0a',
    messagingSenderId: '679818120383',
    projectId: 'gamestagram-1b697',
    storageBucket: 'gamestagram-1b697.firebasestorage.app',
    iosBundleId: 'com.example.gamestagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApRcwZ8nFQYkMLO4tNVvEnN_vBGRtgPPw',
    appId: '1:679818120383:web:9dc2728f733ca1afeb0a0a',
    messagingSenderId: '679818120383',
    projectId: 'gamestagram-1b697',
    authDomain: 'gamestagram-1b697.firebaseapp.com',
    storageBucket: 'gamestagram-1b697.firebasestorage.app',
    measurementId: 'G-BXHGHDRJXR',
  );
}
